version: '3.1'
services:
  web:
    # build: .
    image: alerta/alerta-web
    # volumes:
      # - $PWD/config/alertad.conf.example:/app/alertad.conf
      # - $PWD/config/alerta.conf.example:/app/alerta.conf
      # - $PWD/config/config.json.example:/web/config.json
    ports:
      - 9080:8080
    volumes:
      - $PWD/config/alertad.conf:/app/alertad.conf
    depends_on:
      - db
    environment:
      # - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=mongodb://db:27017/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io
      - ADMIN_PASSWORD=super-secret # default is "alerta"
      - ADMIN_KEY=demo-key  # assigned to first user in ADMIN_USERS
      - ADMIN_KEY_MAXAGE=500
      # - PLUGINS=remote_ip,reject,heartbeat,blackout,normalise,enhance
    restart: always
  db:
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    restart: always
